### PR TITLE
Remove the concept of Asset

### PR DESCRIPTION
**Pull request by somniumism**
The concept of Asset is not necessary for the Foundry.

### CODE REVIEW

**Comment by somniumism** [comment]
Can I change the name of `PlatformAddress` to `Address`?

**Comment by HoOngEe** [comment]
The change seems fine, let's rename the variables in additional commits

**Comment by somniumism** [comment]
I confused this PR with [foundry-primitives-js #7](https://github.com/CodeChain-io/foundry-primitives-js/pull/7). This PR does not have the name `PlatformAddress`. Is there any part you want to change the name?

**Comment by HoOngEe** [comment]
However, It contains variable names starts with `platform~`, I think we'd better to remove the prefix which is now meaningless.

**Comment by somniumism** [comment]
I renamed `platform` to `keystore` in CCkey, because `platform`'s type is KeyStore

**Review by HoOngEe — APPROVED** [review]

**Pull request merged**
